name: CI Build Caddy
on:
  push:
    branches: ['main']
    paths:
      - 'caddy/main/**'
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
jobs:
  BuildX:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      attestations: read
    env:
      REGISTRY: ghcr.io
    defaults:
      run:
        working-directory: ./caddy/main/
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Parse ARGs from Repository
        id: prepare
        shell: bash
        run: |
          if [ ! -f "Dockerfile" ]; then
            echo "Error: No such file or directory"
            exit 1
          fi
          OS_BASE=$(grep -E '^FROM' Dockerfile | head -n 1 | sed 's#^FROM[[:space:]]\(.*\):\(.*\)#\1#')
          OS_VERS=$(grep -E '^FROM' Dockerfile | head -n 1 | sed 's#^FROM[[:space:]]\(.*\):\(.*\)#\2#')
          PD_NAME=$(grep -E '^ENV' Dockerfile | head -n 1 | sed 's#^ENV[[:space:]]\(.*\)_\(.*\)$#\1#' | tr '[:upper:]' '[:lower:]')
          PD_VERS=$(grep -E '^ENV' Dockerfile | head -n 1 | sed 's#^ENV[[:space:]]\(.*\)_\(.*\)=v\(.*\)$#\3#')
          # check if values are empty
          if [ -z "$OS_BASE" ] || [ -z "$OS_VERS" ] || [ -z "$PD_NAME" ] || [ -z "$PD_VERS" ]; then
            echo "Error: One or more required ARG values are empty"
            exit 1
          fi
          # debug results
          echo "BaseOS:  '${OS_BASE}':'${OS_VERS}'"
          echo "Product: '${PD_NAME}':'${PD_VERS}'"
          # set outputs
          echo "os_base=${OS_BASE}" >> $GITHUB_OUTPUT
          echo "os_vers=${OS_VERS}" >> $GITHUB_OUTPUT
          echo "pd_name=${PD_NAME}" >> $GITHUB_OUTPUT
          echo "pd_vers=${PD_VERS}" >> $GITHUB_OUTPUT
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          file: ./caddy/main/Dockerfile
          context: ./caddy/main/
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ steps.prepare.outputs.pd_name }}:${{ steps.prepare.outputs.pd_vers }}-${{ steps.prepare.outputs.os_base }}${{ steps.prepare.outputs.os_vers }}
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ steps.prepare.outputs.pd_name }}:${{ steps.prepare.outputs.pd_vers }}-${{ steps.prepare.outputs.os_base }}
      - name: Cleanup Untagged Images
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          delete-untagged: true
          owner: ${{ github.repository_owner }}
          token: ${{ secrets.GITHUB_TOKEN }}
          package: ${{ steps.prepare.outputs.pd_name }}