name: CI Build HAProxy
on:
  push:
    branches: ['main']
    paths:
      - 'haproxy/**'
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
jobs:
  BuildX:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io
      BASE_IMAGE: 'alpine'
      ALPINE_VER: '3.21'
      PRODUCT_NAME: 'haproxy'
      PRODUCT_VERSION: '3.0.12'
    defaults:
      run:
        working-directory: ./haproxy/
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Parse ARGs from Repository
        id: prepare
        shell: bash
        run: |
          if [ ! -f "ARGs" ]; then
            echo "Error: No such file or directory"
            exit 1
          fi
          AL_VER=$(grep -E '^ALPINE_VERSION=' ARGs | head -n 1 | sed 's/^ALPINE_VERSION=\(.*\)/\1/')
          PD_NME=$(grep -E '^PRODUCT_NAME=' ARGs | head -n 1 | sed 's/^PRODUCT_NAME=\(.*\)/\1/')
          PD_VER=$(grep -E '^PRODUCT_VERSION=' ARGs | head -n 1 | sed 's/^PRODUCT_VERSION=\(.*\)/\1/')
          PD_DIR=$(echo "$PD_VER" | cut -d. -f1,2)
          # check if values are empty
          if [ -z "$AL_VER" ] || [ -z "$PD_VER" ] || [ -z "$PD_NME" ]; then
            echo "Error: One or more required ARG values are empty"
            exit 1
          fi
          # debug results
          echo "ALPINE_VER='${AL_VER}'"
          echo "PRODUCT_NAME='${PD_NME}'"
          echo "PRODUCT_VER='${PD_VER}'"
          echo "DIR='${PD_DIR}'"
          # set outputs
          echo "al_ver=${AL_VER}" >> $GITHUB_OUTPUT
          echo "pd_ver=${PD_VER}" >> $GITHUB_OUTPUT
          echo "pd_nme=${PD_NME}" >> $GITHUB_OUTPUT
          echo "pd_dir=${PD_DIR}" >> $GITHUB_OUTPUT
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64, linux/arm64
          context: ./haproxy/${{ steps.prepare.outputs.pd_dir }}/
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ steps.prepare.outputs.pd_nme }}:${{ steps.prepare.outputs.pd_ver }}-alpine${{ steps.prepare.outputs.al_ver }}
      - name: Cleanup Untagged Images
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          delete-untagged: true
          owner: ${{ github.repository_owner }}
          token: ${{ secrets.GITHUB_TOKEN }}
          package: ${{ steps.prepare.outputs.pd_nme }}